repos:
  - name: gg
    path: /home/ces/.dots/
    url: git@github.com:cafkafk/gg.git
    clone: true
  - name: li
    path: /home/ces/org/src/git/
    url: git@github.com:cafkafk/li.git
    clone: true
  - name: qmk_firmware
    path: /home/ces/org/src/git/
    url: git@github.com:cafkafk/qmk_firmware.git
    clone: true
  - name: starship
    path: /home/ces/org/src/git/
    url: https://github.com/starship/starship.git
    clone: true
links:
  - name: gg
    rx: /home/ces/.config/gg
    tx: /home/ces/.dots/gg
  - name: starship
    rx: /home/ces/.config/starship.toml
    tx: /home/ces/.dots/starship.toml
